# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 401ca9e1a42428731cc9ab176dacc5f95103914d972b0f01f2a95bac650b90fed2628eb1280d6e031172c31ae849669ec25af478834d1c8de18b0ae03eb8ea82

test:
  secret_key_base: d0f5239deeab640e59a87cb5558fedea4107716c827ffae0834fee15b388b7e1442694e55c834aaa9d0bd9d8b663d5d8e3408ee6aba538937604da3bc8d00f6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
