# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adf950928d1b619ef48f4cd32231f65abfe6c8e568290a6e060b4c23f538a4590243bb12bc0491d0617a3baecdb202b2542d818ed8fa9b0b78673fbca566e1cb

test:
  secret_key_base: 71d14d734cdb5f52a0965749a8d7eb516d3daa8dcbb619708178fb4f8a191fa0090697799baa7befaf650d61f8e7825251547e763d1cb5437d0a79f5c3ffcda0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
